[template]
src = "global.tmpl"
dest = "/etc/nginx/conf.d/global.conf"
keys = [
  "/nginx/cqa_dev/34874f35-90f7-4722-9eb9-83a4e4c4f1fd"
]
#check_cmd = "/usr/sbin/nginx -t"
#reload_cmd = "nginx -s reload"
